### ISSUE TITLE
Error on the model.generate() line:  `AttributeError: 'GELU' object has no attribute 'approximate'

### ISSUE THREAD

**Issue by roboswell** [mlfoundations/open_flamingo#189]
When using Pytorch 2.0.0, I receiven error on the model.generate() line, that states:
 
`AttributeError: 'GELU' object has no attribute 'approximate'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) 
local_rank: 0 (pid: 19) of binary: /opt/conda/bin/python`

## Current Behavior

Here's the full error:

Traceback (most recent call last):
  File "/container_working_directory/open_flamingo_9b.py", line 239, in <module>
    generated_text = model.generate(
  File "/opt/conda/lib/python3.10/site-packages/open_flamingo/src/flamingo.py", line 152, in generate
    self._encode_vision_x(vision_x=vision_x)
  File "/opt/conda/lib/python3.10/site-packages/open_flamingo/src/flamingo.py", line 195, in _encode_vision_x
    vision_x = self.perceiver(vision_x)  # reshapes to (b, T, n, d)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/open_flamingo/src/helpers.py", line 131, in forward
    latents = ff(latents) + latents
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/activation.py", line 685, in forward
    return F.gelu(input, approximate=self.approximate)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(

AttributeError: 'GELU' object has no attribute 'approximate'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) 
local_rank: 0 (pid: 19) of binary: /opt/conda/bin/python

Traceback (most recent call last):
  File "/opt/conda/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.0.0', 'console_scripts', 'torchrun')())
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

## Environment

Python 3.10, Pytorch 2.0.0, CUDA 11.7, cuDNN8 Runtime
## Detailed Description

**The error occurs with Pytorch 2.0.0. It goes away if you downgrade to Pytorch 1.10.0, CUDA 11.3, cuDNN 8 Runtime**

**Comment by jpgard** [comment]
This seems like a misconfigured environment. Are you using the coda environment we provided in `environment.yml`?
